# PCA

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# load csv file
df = pd.read_csv('./dataset/seeds_dataset.csv', header=None)
df = df.drop([7], axis=1)

print(df.head())

X = np.array(df)
pca = PCA(n_components=3)
pca.fit(X)
X_reduced = pca.transform(X)

print('singular values is {}'.format(pca.singular_values_))
print('after pca, all of data is reduced to 3D')
print(X_reduced)


       0      1       2      3      4      5      6
0  15.26  14.84  0.8710  5.763  3.312  2.221  5.220
1  14.88  14.57  0.8811  5.554  3.333  1.018  4.956
2  14.29  14.09  0.9050  5.291  3.337  2.699  4.825
3  13.84  13.94  0.8955  5.324  3.379  2.259  4.805
4  16.14  14.99  0.9034  5.658  3.562  1.355  5.175
singular values is [ 47.49531899  21.09635322   3.92284041]
after pca, all of data is reduced to 3D
[[  6.63448376e-01  -1.41732098e+00   4.12356541e-02]
 [  3.15666512e-01  -2.68922915e+00   2.31726953e-01]
 [ -6.60499302e-01  -1.13150635e+00   5.27087232e-01]
 [ -1.05527590e+00  -1.62119002e+00   4.37015260e-01]
 [  1.61999921e+00  -2.18338442e+00   3.33990920e-01]
 [ -4.76938007e-01  -1.33649437e+00   3.55360614e-01]
 [ -1.84834720e-01  -1.50364411e-01   1.41497264e-01]
 [ -7.80629616e-01  -1.12979883e+00   2.79757608e-01]
 [  2.28210810e+00  -1.36001690e+00  -3.50729413e-01]
 [  1.97854147e+00  -1.49468793e+00  -2.93947251e-03]
 [  3.69122947e-01   8.86722511e-01   1.13264978