# 黑白數字辨識
擷取6*6區域內的黑點總和數進行圖像縮減

![alt text](./images/ML_01.jpg)

![alt text](./images/ML_02.jpg)

![alt text](./images/ML_03.jpg)

![alt text](./images/ML_04.jpg)

In [27]:
images.shape

(100, 240, 240)

In [26]:
import cv2
import os
import numpy as np
num=100
row=240
col=240
images = np.zeros((num,row,col))
idx=0

for i in range(10):
    for file in os.listdir("./data/{}".format(i)):
        if file.endswith(".bmp"):
            images[idx,:,:] = cv2.imread("./data/{}".format(i) + "/"+ os.path.join(file) , 0)
            idx += 1
            print(os.path.join(file))

0-1.bmp
0-10.bmp
0-2.bmp
0-3.bmp
0-4.bmp
0-5.bmp
0-6.bmp
0-7.bmp
0-8.bmp
0-9.bmp
1-1.bmp
1-10.bmp
1-2.bmp
1-3.bmp
1-4.bmp
1-5.bmp
1-6.bmp
1-7.bmp
1-8.bmp
1-9.bmp
2--2.bmp
2-1.bmp
2-10.bmp
2-3.bmp
2-4.bmp
2-5.bmp
2-6.bmp
2-7.bmp
2-8.bmp
2-9.bmp
3-1.bmp
3-10.bmp
3-2.bmp
3-3.bmp
3-4.bmp
3-5.bmp
3-6.bmp
3-7.bmp
3-8.bmp
3-9.bmp
4-1.bmp
4-10.bmp
4-2.bmp
4-3.bmp
4-4.bmp
4-5.bmp
4-6.bmp
4-7.bmp
4-8.bmp
4-9.bmp
5-1.bmp
5-10.bmp
5-2.bmp
5-3.bmp
5-4.bmp
5-5.bmp
5-6.bmp
5-7.bmp
5-8.bmp
5-9.bmp
6-1.bmp
6-10.bmp
6-2.bmp
6-3.bmp
6-4.bmp
6-5.bmp
6-6.bmp
6-7.bmp
6-8.bmp
6-9.bmp
7-1.bmp
7-10.bmp
7-2.bmp
7-3.bmp
7-4.bmp
7-5.bmp
7-6.bmp
7-7.bmp
7-8.bmp
7-9.bmp
8-1.bmp
8-10.bmp
8-2.bmp
8-3.bmp
8-4.bmp
8-5.bmp
8-6.bmp
8-7.bmp
8-8.bmp
8-9.bmp
9-1.bmp
9-10.bmp
9-2.bmp
9-3.bmp
9-4.bmp
9-5.bmp
9-6.bmp
9-7.bmp
9-8.bmp
9-9.bmp


In [28]:
print(images.shape)

(100, 240, 240)


In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# read image data 
s='./data/'  

# write your code here

print(images.shape)  

(100, 240, 240)


In [42]:
images[0,:,:]

array([[255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       ...,
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.]])

In [31]:
tmp = images[1,:,:]

In [41]:
tmp2 = np.split(tmp , 6 , axis=0) 
for i in range(6):
    print(np.split(tmp2[i] , 6 , axis=1)[0].shape)
    print(np.split(tmp2[i] , 6 , axis=1)[0].size - np.count_nonzero(np.split(tmp2[i] , 6 , axis=1)[0]) )

(40, 40)
0
(40, 40)
0
(40, 40)
0
(40, 40)
0
(40, 40)
0
(40, 40)
0


In [43]:
np.array(range(36))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [54]:
# extract each image as feature vector
# use 6*6 grid to represent each origin image

# write your code here
tmp_array = np.empty
dataset = np.zeros((100,36))

for n in range(images.shape[0]):
    tmp1 = images[n,:,:]
    tmp2 = np.split(tmp1 , 6 , axis=0) 
    tmp_cnt_array = []
    for i in range(6):
        for j in range(6):
            tmp_cnt_array.append(np.split(tmp2[i] , 6 , axis=1)[j].size - np.count_nonzero(np.split(tmp2[i] , 6 , axis=1)[j]))
#             print(tmp_cnt_array)
#     print(tmp_cnt_array)   
    dataset[n,:] = tmp_cnt_array
    
labels = np.asarray([int(i/10)  for i in range(0,100)])
print(dataset.shape)
print(labels.shape)

(100, 36)
(100,)


In [55]:
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.svm import SVC
# split data into training data and testing data


# write your code here
X = dataset
y = labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(80, 36)
(80,)
(20, 36)
(20,)


In [56]:
# build model and evaluate your result

# write your code here
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

# we can change kernel to rbf, poly, linear
model = SVC(kernel='rbf', C=1.3)
model.fit(X_train, y_train)

X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)

print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('con_matrix: {}'.format(con_matrix))

number of correct sample: 16
accuracy: 0.8
con_matrix: [[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0]
 [0 0 0 2 0 2 0 0 0]
 [0 0 0 0 3 2 0 0 0]
 [0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 1]]
