# Logistic Regression  
IRIS dataset description:  
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html    
https://scikit-learn.org/stable/datasets/index.html#iris-dataset  
logistic regression model:   
http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html 

In [1]:
import numpy as np
from sklearn.linear_model  import LogisticRegression
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix

# import some data to play with
iris = datasets.load_iris()

#X = iris.data[:, :2]  # we only take the first two features.
X = iris.data
y = iris.target
#print(X.shape)
#print(y)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1) #random_state 種子值

scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

model=LogisticRegression()
model.fit(X_train,y_train)

X_test_nor = scaler.transform(X_test)
y_pred = model.predict(X_test_nor)
accuracy = accuracy_score(y_test, y_pred)

print(model.coef_)
#print prediction result
print(y_pred)
#print accuracy 
print(accuracy)

from joblib import dump, load
dump(model, 'logistic_model.joblib') 

[[-1.0169518   0.93320063 -1.71063824 -1.57995617]
 [ 0.64186897 -0.48170874 -0.2674308  -0.708515  ]
 [ 0.37508284 -0.4514919   1.97806903  2.28847117]]
[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 1 2 1]
0.9555555555555556


['logistic_model.joblib']

In [2]:
logistic_model = load('logistic_model.joblib') 

y_pred = logistic_model.predict(X_test_nor)
accuracy = logistic_model.score(X_test_nor, y_test)

print(model.coef_)
#print prediction result
print(y_pred)
#print accuracy 
print(accuracy)

[[-1.0169518   0.93320063 -1.71063824 -1.57995617]
 [ 0.64186897 -0.48170874 -0.2674308  -0.708515  ]
 [ 0.37508284 -0.4514919   1.97806903  2.28847117]]
[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 1 2 1]
0.9555555555555556


In [4]:
# Logistic Regression  
# IRIS dataset description:  
# https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html    
# https://scikit-learn.org/stable/datasets/index.html #iris-dataset  
# logistic regression model:   
# http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html 

import numpy as np
from sklearn.linear_model  import LogisticRegression
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix

# import some data to play with
iris = datasets.load_iris()

#X = iris.data[:, :2]  # we only take the first two features.
X = iris.data
y = iris.target
#print(X.shape)
#print(y)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1) #random_state 種子值

scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

model=LogisticRegression()
model.fit(X_train,y_train)

X_test_nor = scaler.transform(X_test)
y_pred = model.predict(X_test_nor)
accuracy = accuracy_score(y_test, y_pred)

print(model.coef_)
#print prediction result
print(y_pred)
#print accuracy 
print(accuracy)

from joblib import dump, load
dump(model, 'logistic_model.joblib') 

logistic_model = load('logistic_model.joblib') 

y_pred = logistic_model.predict(X_test_nor)
accuracy = logistic_model.score(X_test_nor, y_test)

print(model.coef_)
#print prediction result
print(y_pred)
#print accuracy 
print(accuracy)

[[-1.0169518   0.93320063 -1.71063824 -1.57995617]
 [ 0.64186897 -0.48170874 -0.2674308  -0.708515  ]
 [ 0.37508284 -0.4514919   1.97806903  2.28847117]]
[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 1 2 1]
0.9555555555555556
[[-1.0169518   0.93320063 -1.71063824 -1.57995617]
 [ 0.64186897 -0.48170874 -0.2674308  -0.708515  ]
 [ 0.37508284 -0.4514919   1.97806903  2.28847117]]
[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 1 2 1]
0.9555555555555556
